# Generated by Django 4.2.6 on 2023-11-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='poll',
            name='image',
            field=models.FileField(null=True, upload_to='poll_images'),
        ),
    ]
