# Generated by Django 4.2.6 on 2023-11-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_text_poll_title_poll_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_image',
            field=models.ImageField(null=True, upload_to='choice_details_pictures'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
