# Generated by Django 4.2.6 on 2023-11-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_choice_choice_description_choice_choice_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='image',
            field=models.FileField(help_text='Upload an image with 600x600 resolution', null=True, upload_to='poll_images'),
        ),
    ]
